Global:
  use_gpu: True
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/srn_vn
  save_epoch_step: 20
  eval_batch_step:
  - 3000
  - 4000
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints: 
  save_inference_dir: ./inference/SRN
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ./ppocr/utils/dict/vi_vietnam.txt
  character_type: vi
  max_text_length: 25
  num_heads: 8
  infer_mode: false
  use_space_char: true
  save_res_path: ./output/srn_vn/predicts_srn.txt
  load_static_weights: true
  distributed: false

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform: null
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512
Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/vietnamese/img_crop
    label_file_list:
    - ./train_data/vietnamese/crop_label.txt
    ratio_list:
    - 1
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - SRNLabelEncode: null
    - SRNRecResizeImg:
        image_shape:
        - 1
        - 64
        - 256
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - encoder_word_pos
        - gsrm_word_pos
        - gsrm_slf_attn_bias1
        - gsrm_slf_attn_bias2
  loader:
    shuffle: false
    batch_size_per_card: 32
    drop_last: false
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/vietnamese/img_crop
    label_file_list:
    - ./train_data/vietnamese/crop_label.txt
    ratio_list:
    - 1
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - SRNLabelEncode: null
    - SRNRecResizeImg:
        image_shape:
        - 1
        - 64
        - 256
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - encoder_word_pos
        - gsrm_word_pos
        - gsrm_slf_attn_bias1
        - gsrm_slf_attn_bias2
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 4